# Generated by Django 3.2.4 on 2021-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_app_app_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
