# Generated by Django 3.2.4 on 2021-07-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_app_app_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
